server {
	# The server listens for incoming HTTPS traffic on port 443 for both IPv4 and IPv6 addresses
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name www.piyu.42.fr piyu.42.fr;

	# The locations of the SSL/TLS certificate and key, used for encrypting the traffic
	ssl_certificate		/etc/nginx/ssl/inception.crt;
	ssl_certificate_key	/etc/nginx/ssl/inception.key;

	# TLS 1.3 is the most secure and fastest version of the TLS protocol
	ssl_protocols TLSv1.3;

	# The root directory where Nginx looks for files
	root	/var/www/html;

	# The default file that Nginx serves
	index	index.php;

	# Nginx receives the path after the domain as the URI, e.g. for `login.42.fr/about/`, it receives
	# the request `GET /about/`. And it looks for the file under the root directory, `/var/www/html/about/`.
	# `location` searches for matching patterns. `/` means any request.
	# `try_files` applies a three-step fallback chain: first try to serve the exact file, then try to
	# serve it as a directory, and fall back to index.php if no match found, also passing along any
	# query string arguments as WordPress uses them to decide what content to show
	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	# This block handles requests ending in `.php`. The `~` means it's a case-sensitive regex match.
	# When the file doesn't exist, it returns 404 instead of passing it to PHP.
	# The rest is FastCGI config as PHP-FPM communicates using FastCGI protocol.
	location ~ \.php$ {
		# Return 404 if the PHP file does not exist
		try_files $uri =404;

		include fastcgi_params;
		fastcgi_pass wordpress:9000;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}
}

