server {
	# The server listens for incoming HTTPS traffic on port 443 for both IPv4 and IPv6 addresses
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name www.piyu.42.fr piyu.42.fr

	# The locations of the SSL/TLS certificate and key, used for encrypting the traffic
	ssl_certificate		/etc/nginx/ssl/inception.crt;
	ssl_certificate_key	/etc/nginx/ssl/inception.key;

	# TLS 1.3 is the most secure and fastest version of the TLS protocol
	ssl_protocols TLSv1.3;

	# The root directory where Nginx looks for files
	root	/var/www/html;

	# The default file that Nginx serves
	index	index.php;

	# Fall back to index.php if no match (WordPress relies on query arguments)
	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	# PHP-FPM communicates using FastCGI protocol
	location ~ \.php$ {
		# Return 404 if the PHP file does not exist
		try_files $uri =404;

		include fastcgi_params;
		fastcgi_pass wordpress:9000;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}
}
