[www]

; The existing unprivileged user for Alpine
user = nobody
group = nobody

; Listen on all network interfaces' port 9000. So Nginx can reach PHP-FPM
; over the Docker network regardless of its assigned internal IP address
listen = 0.0.0.0:9000

; These are only relevant for Unix sockets
;listen.owner = nobody
;listen.group = nobody

; Dynamically scale the number of PHP-FPM worker processes
pm = dynamic
; Never have more than 5 workers
pm.max_children = 5
pm.start_servers = 2
; Keep at least 1 idle worker available
pm.min_spare_servers = 1
; If more than 3 workers are sitting idle, terminate some to save memory
pm.max_spare_servers = 3

; Allow environment variables to remain available to PHP if needed
clear_env = no
